### ISSUE TITLE
Ошибка при установке через композер на Symfony 5

### ISSUE THREAD

**Issue by Koroalen** [Velhron/dadata-bundle#10]
Script cache:clear returned with error code 1
!!
!!  In VelhronDadataExtension.php line 25:
!!
!!    Notice: Undefined index: token

**Comment by Koroalen** [comment]
Ошибка на этапе cache:clear из-за отсутствия конфигурационного файлa  bundleName.yaml
Странно, что не сработал рецепт по созданию конфиг файла.

**Comment by Velhron** [comment]
@Koroalen я сегодня всё проверю
