### ISSUE TITLE
iplocateAddress() игнорирует переданный параметр

### ISSUE THREAD

**Issue by nalgeon** [Velhron/dadata-bundle#8]
Метод `$dadataIplocate->iplocateAddress($ip)` игнорирует значение переданного IP-адреса. Насколько мне удалось понять по коду, он передает значение в GET-параметре с названием `query`, а «Дадата» ожидает параметр с названием `ip` (см. [документацию](https://dadata.ru/api/iplocate/)). Поэтому, хотя формально IP-адрес уходит в «Дадату», де-факто он игнорируется.

Решение — передавать IP-адрес в GET-параметре с названием `ip`, как ожидает «Дадата».

**Comment by Velhron** [comment]
Добрый день. 
Спасибо за замечание. Сегодня всё проверю и залью фикс

**Comment by Velhron** [comment]
Добрый день. 
Создал новый релиз. Спасибо.

**Comment by nalgeon** [comment]
Большое спасибо за фикс и за новые методы!
